"""Regenerate the built-in station snapshot (backend/stations.py) from the Region List sheet downloaded as CSV.

    python scripts/gen_stations.py "C:/path/to/Region List - Region.csv"

The snapshot is only the FALLBACK: the app reads the sheet itself (an admin pastes the published CSV link or uploads the file under Admin -> Documents -> Station
list, see backend/region_list.py), so this needs running only now and then to keep what a fresh install starts with close to the sheet. Same rules as the app:
Active / Virtual rows in Klang Valley, Northern, Southern, East Coast and East Malaysia; Closed and non-Last-Mile groups (SAMEDAY, NO HUB) are left out.
"""
import csv
import os
import sys
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "backend"))
os.environ.pop("DATABASE_URL", None)

import region_list  # noqa: E402

HEAD = '''"""Static reference data: nationwide hub codes -> station name / zone / region.

The BUILT-IN snapshot of the "Region List" master sheet ({n} Last Mile stations across {regions} regions, snapshot {today}); generated by
scripts/gen_stations.py -- do not hand-edit. It is only the fallback: at run time backend/region_list.py replaces it with the sheet itself (published CSV link) or with
the file an admin uploaded (Admin -> Documents -> Station list), so a station opening or closing does not need a code change.
Everything below the table is derived from HUBS and is rebuilt IN PLACE by replace_hubs(), so `from stations import HUBS, REGIONS, ...` in other modules keeps working.
"""

# hub_code -> (station_name, station_name_full, zone, region)
HUBS: dict[str, tuple[str, str, str, str]] = {{
'''

TAIL = '''}

BUNDLED_HUBS: dict[str, tuple[str, str, str, str]] = dict(HUBS)

REGIONS: list[str] = []
ZONES_BY_REGION: dict[str, list[str]] = {}
ZONES: list[str] = []

# Full station name (as used by Redash queries like "OPEX: Total Shipments & Parcels
# by Hub" and "FLEET: LM Delivery Performance", e.g. "Station Larkin") -> hub code.
# Lookup is case-insensitive; not every row in those queries matches a known station
# (some are non-network partner locations) -- unmatched rows are simply skipped.
FULL_NAME_TO_HUB: dict[str, str] = {}

# Short station abbreviation (the 2nd hyphen-separated segment of a hub code, e.g.
# "LKN" in "C1-LKN-13-67") -> hub code. This is the code drivers' names are prefixed
# with in query 512 (e.g. "HTM - HD - AIZAT"), so it's how attendance/driver rows get
# matched back to a home station.
ABBR_TO_HUB: dict[str, str] = {}


def _derive() -> None:
    """Rebuild everything derived from HUBS, in place (other modules hold references to these objects)."""
    REGIONS[:] = sorted({v[3] for v in HUBS.values()})
    by_region: dict[str, set[str]] = {}
    for _name, _full, zone, region in HUBS.values():
        by_region.setdefault(region, set()).add(zone)
    ZONES_BY_REGION.clear()
    ZONES_BY_REGION.update({r: sorted(zs) for r, zs in sorted(by_region.items())})
    ZONES[:] = sorted({v[2] for v in HUBS.values()})
    FULL_NAME_TO_HUB.clear()
    FULL_NAME_TO_HUB.update({v[1].lower(): k for k, v in HUBS.items()})
    ABBR_TO_HUB.clear()
    ABBR_TO_HUB.update({hub.split("-")[1]: hub for hub in HUBS if len(hub.split("-")) > 1})


def replace_hubs(new: dict[str, tuple[str, str, str, str]]) -> bool:
    """Swap the station list for `new` (same shape as HUBS); True when anything changed. Stations that stay are not touched, so a reader that is
    part-way through the dict never sees it empty."""
    if new == HUBS:
        return False
    for code in [c for c in HUBS if c not in new]:
        del HUBS[code]
    HUBS.update(new)
    _derive()
    return True


_derive()


def station_lookup(hub_code: str) -> tuple[str, str, str, str] | None:
    return HUBS.get(hub_code)
'''


def main(path: str) -> None:
    with open(path, encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        # the sheet has a second little table to the right with blank / numeric headers: name every column so dict rows are safe
        names = [h if h.strip() and not h.strip().isdigit() else f"_col{i}" for i, h in enumerate(header)]
        rows = [dict(zip(names, r)) for r in reader]
    hubs, report = region_list.parse(rows)
    if len(hubs) < region_list.MIN_STATIONS:
        raise SystemExit(f"Only {len(hubs)} stations found -- is this the Region List CSV?")
    out = HEAD.format(n=len(hubs), regions=len({v[3] for v in hubs.values()}), today=date.today().isoformat())
    last_region = None
    for code, (name, full, zone, region) in hubs.items():
        if region != last_region:
            out += f"    # {region}\n"
            last_region = region
        out += f"    {code!r}: ({name!r}, {full!r}, {zone!r}, {region!r}),\n"
    out += TAIL
    with open(os.path.join(ROOT, "backend", "stations.py"), "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    print(f"backend/stations.py: {len(hubs)} stations  {report['by_region']}  closed {report['closed']}  left out (not Last Mile): {report['not_last_mile']}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
