-- 2026-10-07: Station Profile (header tab). The things the MY - Fleet Management sheet's 'Station' tab shows for one station that are not kept anywhere else yet:
--  * station_profile: the Warehouse ID per station (the sheet's control tab; Station ID is the premises station_code, address / launch date / chat space are premises);
--  * profile_info: the same-for-every-station boxes -- WORKMAIL GROUP, MANAGER ON DUTY, BUSINESS HOURS -- as JSON, edited by the Fleet Admin Team Lead;
--  * station_postcodes: the postcodes a station covers, loaded from the [MY] Master Postcodes sheet (upload in the tab; empty until then).
-- The INSERTs below are real reference data (not test data): they are meant for production too.
CREATE TABLE station_profile (
  station      VARCHAR(100) NOT NULL,
  warehouse_id VARCHAR(20)  NULL,
  updated_by   VARCHAR(255) NULL,
  updated_at   DATETIME     NULL,
  PRIMARY KEY (station)
);

CREATE TABLE profile_info (
  info_key   VARCHAR(40)  NOT NULL,
  info_value TEXT         NOT NULL,
  updated_by VARCHAR(255) NULL,
  updated_at DATETIME     NULL,
  PRIMARY KEY (info_key)
);

CREATE TABLE station_postcodes (
  station  VARCHAR(100) NOT NULL,
  postcode VARCHAR(10)  NOT NULL,
  PRIMARY KEY (station, postcode)
);

INSERT INTO station_profile (station, warehouse_id, updated_by) VALUES
  ('Ajil', '13', 'migration V75'),
  ('Alor Gajah', '89', 'migration V75'),
  ('Alor Setar', '37', 'migration V75'),
  ('Ampang', '105', 'migration V75'),
  ('Ara Damansara', '110', 'migration V75'),
  ('Ayer Hitam', '81', 'migration V75'),
  ('Bachok', '3', 'migration V75'),
  ('Bagan Serai', '58', 'migration V75'),
  ('Bahau', '82', 'migration V75'),
  ('Baling', '39', 'migration V75'),
  ('Bandar Mahkota Cheras', '142', 'migration V75'),
  ('Bandar Tun Razak', '125', 'migration V75'),
  ('Bangi', '128', 'migration V75'),
  ('Bangsar', NULL, 'migration V75'),
  ('Banting', '132', 'migration V75'),
  ('Batu Gajah', '49', 'migration V75'),
  ('Batu Kawa', '171', 'migration V75'),
  ('Batu Pahat', '80', 'migration V75'),
  ('Bayan Lepas', '45', 'migration V75'),
  ('Beaufort', '160', 'migration V75'),
  ('Bentong', '146', 'migration V75'),
  ('Bintulu', '181', 'migration V75'),
  ('Botanik', '139', 'migration V75'),
  ('Bukit Gambir', '78', 'migration V75'),
  ('Bukit Mertajam', '47', 'migration V75'),
  ('Bukit Payong', '17', 'migration V75'),
  ('Bukit Rahman Putra', NULL, 'migration V75'),
  ('Butterworth', '41', 'migration V75'),
  ('Cameron Highlands', '54', 'migration V75'),
  ('Cheras', '126', 'migration V75'),
  ('Chow Kit', '112', 'migration V75'),
  ('Chukai', '19', 'migration V75'),
  ('Cyberjaya', '123', 'migration V75'),
  ('Dungun', '16', 'migration V75'),
  ('Farlim', '46', 'migration V75'),
  ('Gambang', '28', 'migration V75'),
  ('Gelang Patah', '64', 'migration V75'),
  ('Gemas', '87', 'migration V75'),
  ('Georgetown', '44', 'migration V75'),
  ('Gerik', '56', 'migration V75'),
  ('Gong Badak', '11', 'migration V75'),
  ('Gua Musang', '10', 'migration V75'),
  ('Gurun', '33', 'migration V75'),
  ('Inanam', '148', 'migration V75'),
  ('Ipoh', '61', 'migration V75'),
  ('Jasin', '91', 'migration V75'),
  ('Jengka', '24', 'migration V75'),
  ('Jerantut', '23', 'migration V75'),
  ('Jerteh', '9', 'migration V75'),
  ('Jitra', '36', 'migration V75'),
  ('Kajang', '102', 'migration V75'),
  ('Kangar', '35', 'migration V75'),
  ('Kempas', '74', 'migration V75'),
  ('Keningau', '152', 'migration V75'),
  ('Kepala Batas', '42', 'migration V75'),
  ('Kepong', '115', 'migration V75'),
  ('Ketereh', '2', 'migration V75'),
  ('Kota Kinabatangan', '166', 'migration V75'),
  ('Klang', '108', 'migration V75'),
  ('Kluang', '76', 'migration V75'),
  ('Kota Bharu', '4', 'migration V75'),
  ('Kota Kemuning', '117', 'migration V75'),
  ('Kota Masai', '70', 'migration V75'),
  ('Kota Tinggi', '62', 'migration V75'),
  ('Kuala Kangsar', '57', 'migration V75'),
  ('Kuala Krai', '7', 'migration V75'),
  ('Kuala Kubu Baru', '134', 'migration V75'),
  ('Kuala Lipis', '29', 'migration V75'),
  ('Kuala Selangor', '131', 'migration V75'),
  ('Kuantan', '18', 'migration V75'),
  ('Kuching', '169', 'migration V75'),
  ('Kulai', '69', 'migration V75'),
  ('Kulim', '40', 'migration V75'),
  ('Labuan', '168', 'migration V75'),
  ('Lahad Datu', '164', 'migration V75'),
  ('Langkawi', '31', 'migration V75'),
  ('Larkin', '72', 'migration V75'),
  ('Machang', '6', 'migration V75'),
  ('Marang', '12', 'migration V75'),
  ('Melaka Tengah', '90', 'migration V75'),
  ('Mersing', '75', 'migration V75'),
  ('Miri', '179', 'migration V75'),
  ('Mount Austin', '67', 'migration V75'),
  ('Muadzam Shah', '27', 'migration V75'),
  ('Muar', '79', 'migration V75'),
  ('Mutiara Damansara', '106', 'migration V75'),
  ('Nilai', '84', 'migration V75'),
  ('Nusajaya', '65', 'migration V75'),
  ('Oug', '101', 'migration V75'),
  ('Paka', '14', 'migration V75'),
  ('Papar', '150', 'migration V75'),
  ('Pasir Gudang', '68', 'migration V75'),
  ('Pasir Mas', '5', 'migration V75'),
  ('Pasir Puteh', '8', 'migration V75'),
  ('Pekan', '26', 'migration V75'),
  ('Penampang', '157', 'migration V75'),
  ('Penawar', '63', 'migration V75'),
  ('Pendang', '38', 'migration V75'),
  ('Petaling Jaya', '114', 'migration V75'),
  ('Petra Jaya', NULL, 'migration V75'),
  ('Pokok Sena', '32', 'migration V75'),
  ('Pontian', '66', 'migration V75'),
  ('Port Dickson', '85', 'migration V75'),
  ('Port Klang', '118', 'migration V75'),
  ('Puchong', '116', 'migration V75'),
  ('Puncak Alam', '135', 'migration V75'),
  ('Rantau Panjang', '143', 'migration V75'),
  ('Raub', '147', 'migration V75'),
  ('Rawang', '120', 'migration V75'),
  ('Rimbayu', '138', 'migration V75'),
  ('Rompin', '25', 'migration V75'),
  ('Salak Tinggi', '133', 'migration V75'),
  ('Samarahan', '175', 'migration V75'),
  ('Sandakan', '149', 'migration V75'),
  ('Saratok', '176', 'migration V75'),
  ('Segamat', '77', 'migration V75'),
  ('Segambut', '129', 'migration V75'),
  ('Selayang', '122', 'migration V75'),
  ('Semenyih', '136', 'migration V75'),
  ('Semporna', '165', 'migration V75'),
  ('Senawang', '83', 'migration V75'),
  ('Sentul', NULL, 'migration V75'),
  ('Sepanggar', NULL, 'migration V75'),
  ('Serdang', '121', 'migration V75'),
  ('Seremban', '86', 'migration V75'),
  ('Setia Alam', '98', 'migration V75'),
  ('Setiu', '15', 'migration V75'),
  ('Shah Alam', '104', 'migration V75'),
  ('Shamelin', '141', 'migration V75'),
  ('Sibu', '170', 'migration V75'),
  ('Simpang Ampat', '43', 'migration V75'),
  ('Sitiawan', '60', 'migration V75'),
  ('Slim River', '50', 'migration V75'),
  ('Subang', '103', 'migration V75'),
  ('Sungai Besar', '137', 'migration V75'),
  ('Sungai Petani', '30', 'migration V75'),
  ('Sunway', '97', 'migration V75'),
  ('Taiping', '59', 'migration V75'),
  ('Taman Desa', '111', 'migration V75'),
  ('Taman Mega Jaya', '113', 'migration V75'),
  ('Tanjung Minyak', '88', 'migration V75'),
  ('Tapah', '51', 'migration V75'),
  ('Tawau', '163', 'migration V75'),
  ('Teluk Intan', '53', 'migration V75'),
  ('Temerloh', '22', 'migration V75'),
  ('Triang', '21', 'migration V75'),
  ('Tuaran', '156', 'migration V75'),
  ('Ulu Tiram', '71', 'migration V75'),
  ('Wakaf Bharu', '1', 'migration V75'),
  ('Wangsa Maju', '107', 'migration V75'),
  ('Melawati', '94', 'migration V75');

INSERT INTO profile_info (info_key, info_value, updated_by) VALUES
  ('workmail_groups', '[{"label": "Fleet Manager", "email": "myhead@ninjavan.co"}, {"label": "Region Head", "email": "myregionhead@ninjavan.co"}, {"label": "Station Head", "email": "my-lastmile-stationheads@ninjavan.co"}, {"label": "My Fleet", "email": "teamfleetmy@ninjavan.co"}, {"label": "Fleet Admin", "email": "my-fleet-admin@ninjavan.co"}, {"label": "Human Resources (HR)", "email": "my-hr-peopleservices@ninjavan.co"}]', 'migration V75'),
  ('managers_on_duty', '[{"area": "COD & Security", "name": "TBA"}, {"area": "SOP, QAHSE & Fleet Training", "name": "Shahrul Hasriq Bin Tajuludin"}, {"area": "Fleet Project Trial", "name": "Nazrul Nazriq Bin Roslan"}, {"area": "Landhaul", "name": "Faizal Zakaria"}, {"area": "Airhaul", "name": "Farah Faisal"}, {"area": "OpEx Last Mile", "name": "Nabilah Zainal"}]', 'migration V75'),
  ('business_hours', '{"delivery_window": "9am - 10pm (7pm - 10pm best effort basis)", "opening_days": "Mon - Sun", "opening_hours": "9am to 7pm"}', 'migration V75');
